# Generated by Django 4.2 on 2023-05-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_user_first_name_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post', 'rater')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_time',
        ),
    ]
