# Generated by Django 3.0.2 on 2023-06-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20230610_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
