# Generated by Django 3.0.2 on 2023-06-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_post_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='network.Tag'),
        ),
    ]
